name: Build Kayan POS to EXE
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # خطوة حاسمة لتثبيت أدوات بناء C++ المتوافقة تماماً مع سيرفر الويندوز
      - name: Install Windows Build Tools
        run: |
          npm install --global windows-build-tools --create-config

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App to EXE
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
